[server]
host = "0.0.0.0"
port = 8080
cors_allow_origin = "null"

[server.tls]
enabled = false
cert_path = "certs/server.crt"
key_path = "certs/server.key"

# Global transcoding settings (can be overridden per camera)
[transcoding]
output_format = "mjpeg"
capture_framerate = 0  # FPS to capture from camera (0 = max available)
send_framerate = 10    # FPS to send to clients
channel_buffer_size = 1 # Number of frames to buffer (1 = only latest frame)
allow_duplicate_frames = false # If false, each frame is sent only once
debug_capture = false    # Enable debug output for capture rate
debug_sending = false   # Enable debug output for sending rate

# Camera configurations
# Each camera has a unique ID and configurable path

[cameras.cam1]
enabled = true  # Optional: Enable/disable this camera (default: true)
path = "/cam1"
url = "rtsp://admin007:admin007@192.168.1.171:554/stream1"
transport = "tcp"
reconnect_interval = 5
chunk_read_size = 32768
#ffmpeg_buffer_size = 65536
#quality = 50  # JPEG quality (1-100), omit to use FFmpeg default
ffmpeg_log_stderr = "console"  # Options: "file", "console", "both", or omit/false to disable

# Optional FFmpeg options (defaults shown, uncomment to override)
[cameras.cam1.ffmpeg_options]
fflags = "" # "+nobuffer+discardcorrupt"
flags = ""
avioflags = "" # "direct"
fps_mode = ""  # Use "cfr" for constant framerate, "vfr" for variable, "passthrough" to keep original
flush_packets = ""
extra_input_args = [] # ["-analyzeduration", "100000", "-probesize", "100000"]
extra_output_args = []

[cameras.cam2]
enabled = false  # Optional: Enable/disable this camera (default: true)
path = "/cam2"
url = "rtsp://admin007:admin007@192.168.1.182:554/stream1"
transport = "tcp"
reconnect_interval = 5
chunk_read_size = 32768
ffmpeg_buffer_size = 65536
#ffmpeg_log_stderr = "file"  # Options: "file", "console", "both", or omit/false to disable

[cameras.cam3]
enabled = false  # Example: This camera is disabled and won't be started
path = "/cam3"
url = "rtsp://admin007:admin007@192.168.1.188:554/stream2"
transport = "tcp"
reconnect_interval = 5
chunk_read_size = 32768
ffmpeg_buffer_size = 65536
#ffmpeg_log_stderr = "file"  # Options: "file", "console", "both", or omit/false to disable
# Camera-specific transcoding override (optional)
quality = 30  # JPEG quality (1-100), omit to use FFmpeg default
# send_framerate = 5

# MQTT Configuration (optional)
[mqtt]
enabled = true
broker_url = "mqtt://192.168.1.4:1883"  # Can also use mqtts:// for TLS
client_id = "videoserver-01"
# username = "mqtt_user"  # Optional
# password = "mqtt_pass"  # Optional
base_topic = "Videoserver"  # Base topic for all MQTT messages
qos = 0  # Quality of Service (0, 1, or 2)
retain = false  # Whether to retain messages
keep_alive_secs = 60  # Keep-alive interval in seconds
publish_interval_secs = 5  # How often to publish status updates