[server]
host = "0.0.0.0"
port = 8080
cors_allow_origin = "null"

[server.tls]
enabled = false
cert_path = "certs/server.crt"
key_path = "certs/server.key"

# MQTT Configuration (optional)
[mqtt]
enabled = true
broker_url = "mqtt://192.168.1.4:1883"  # Can also use mqtts:// for TLS
client_id = "videoserver-01"
# username = "mqtt_user"  # Optional
# password = "mqtt_pass"  # Optional
base_topic = "Videoserver"  # Base topic for all MQTT messages
qos = 0  # Quality of Service (0, 1, or 2)
retain = false  # Whether to retain messages
keep_alive_secs = 60  # Keep-alive interval in seconds
publish_interval_secs = 1  # How often to publish status updates
publish_picture_arrival = true  # Enable/disable picture arrival publishing (default: true)

# Global transcoding settings (can be overridden per camera)
[transcoding]
output_format = "mjpeg"
capture_framerate = 0  # FPS to capture from camera (0 = max available)
send_framerate = 10    # FPS to send to clients
channel_buffer_size = 10 # Number of frames to buffer (1 = only latest frame)
allow_duplicate_frames = false # If false, each frame is sent only once
debug_capture = false    # Enable debug output for capture rate
debug_sending = false   # Enable debug output for sending rate
debug_duplicate_frames = true # Enable/disable duplicate frame warnings

# Camera configurations
# Each camera has a unique ID and configurable path
# 
# Video codec options:
# - output_format: "mjpeg" (default), "mpegts", "mp4", "avi", etc.
# - video_codec: "mpeg1video", "libx264", "libx265", "h264_nvenc", etc.
# - video_bitrate: "200k", "1M", "2000k" (for non-MJPEG codecs)
# - output_framerate: Output FPS (different from capture framerate)
# - gop_size: Keyframe interval (frames between keyframes)
# - quality: JPEG quality 1-100 (mainly for MJPEG format)

####################################################################################################
[cameras.cam1]
enabled = true  # Optional: Enable/disable this camera (default: true)
path = "/cam1"
url = "rtsp://admin007:admin007@192.168.1.171:554/stream1"
transport = "tcp"
reconnect_interval = 5
chunk_read_size = 8192 # 32768
#token = "secure-cam1-token"  # Optional: Token required for WebSocket authentication

# FFmpeg configuration for cam1
[cameras.cam1.ffmpeg]
log_stderr = "file"  # FFmpeg stderr logging: "file", "console", "both"

# Command override - if set, replaces all other FFmpeg options with a custom command
# Placeholder: $url = camera RTSP URL
#command = "-use_wallclock_as_timestamps 1 -rtsp_transport tcp -i $url -an -c:v mjpeg -q:v 4 -vf fps=15 -f mjpeg -"

use_wallclock_as_timestamps = true  # Adds "-use_wallclock_as_timestamps 1" as first option

scale = "640:-1"  # Video scaling: "640:480", "1280:-1", etc.

#output_format = "mjpeg"  # Output format: MJPEG for streaming
#output_framerate = 5  # Output framerate (fps)

#video_codec = "mjpeg"  # Video codec: mjpeg is default for MJPEG format
#video_bitrate = "200k"  # Video bitrate: "200k", "1M", "2000k", etc.
#gop_size = 10  # GOP size (keyframe interval) - frames between keyframes

# FFmpeg advanced options for low latency
#rtbufsize = 65536  # RTSP buffer size in bytes
#fflags = "+nobuffer+discardcorrupt"
#flags = "low_delay"
#avioflags = "direct"
#fps_mode = "cfr"  # Use "cfr" for constant framerate, "vfr" for variable, "passthrough" to keep original
#flush_packets = "1"
#extra_input_args = [] # ["-analyzeduration", "100000", "-probesize", "100000"]
#extra_output_args = []

####################################################################################################
[cameras.cam2]
enabled = true  # Optional: Enable/disable this camera (default: true)
path = "/cam2"
url = "rtsp://admin007:admin007@192.168.1.188:554/stream1"
transport = "tcp"
reconnect_interval = 5
#token = "secure-cam2-token"  # Token required for WebSocket authentication

[cameras.cam2.ffmpeg]
log_stderr = "file"  # FFmpeg stderr logging: "file", "console", "both"
scale = "640:-1"  # Video scaling: "640:480", "1280:-1", etc.

####################################################################################################
[cameras.cam3]
enabled = true  # Optional: Enable/disable this camera (default: true)
path = "/cam3"
url = "rtsp://admin007:admin007@192.168.1.182:554/stream1"
transport = "tcp"
reconnect_interval = 5

[cameras.cam3.ffmpeg]
log_stderr = "file"  # FFmpeg stderr logging: "file", "console", "both"
scale = "640:-1"  # Video scaling: "640:480", "1280:-1", etc.

####################################################################################################
[cameras.cam4]
enabled = true  # Optional: Enable/disable this camera (default: true)
path = "/cam4"
url = "http://Admin007:Admin007%23%23@outdoor2:80/videostream.asf"
transport = "tcp"
reconnect_interval = 5

[cameras.cam4.ffmpeg]
log_stderr = "file"  # FFmpeg stderr logging: "file", "console", "both"
#scale = "640:-1"  # Video scaling: "640:480", "1280:-1", etc.
