[server]
host = "0.0.0.0"
port = 8080
cors_allow_origin = "null"

[server.tls]
enabled = false
cert_path = "certs/server.crt"
key_path = "certs/server.key"

[rtsp]
url = "rtsp://admin007:admin007@192.168.1.171:554/stream2"
transport = "tcp"
reconnect_interval = 5
buffer_size = 1024000

[transcoding]
output_format = "mjpeg"
quality = 85
framerate = 10
max_latency_ms = 200
