[server]
host = "0.0.0.0"
port = 8080
cors_allow_origin = "null"

[server.tls]
enabled = false
cert_path = "certs/server.crt"
key_path = "certs/server.key"

[rtsp]
url = "rtsp://admin007:admin007@192.168.1.171:554/stream2"
transport = "tcp"
reconnect_interval = 5
channel_buffer_size = 100  # Number of frames to buffer in broadcast channel (lower = less latency)
chunk_read_size = 1024   # Bytes to read at once from FFmpeg (8KB default)
ffmpeg_buffer_size = 1024  # FFmpeg RTSP buffer size in bytes (32KB for low latency)

[transcoding]
output_format = "mjpeg"
quality = 50
framerate = 10
